cartao_inserir_sucesso=Foi adicionado um registro para {0} com sucesso.
cartao_atualizar_sucesso=Foi atualizado um registro para {0} com sucesso.
cartao_visualizar_todos=Requisição realizada com sucesso.
cartao_visualizar_nome=Requisição para visualizar dados de {0} realizada com sucesso.
cartao.remover.id=Foi removido da base de dados, o registro id {0}.