cartao.valor.not.null=O campo valor não pode ser nulo.
cartao.valor.min=O valor deve ser maior que zero.
cartao.nome.obrigatorio=O nome dever ser obrigatorio (Raphael,Rhaissa ou Ambos)
cartao.not.found=Não existe cartão com id {0} na base de dados.
